name: Changesets

on: [pull_request]
jobs:
  changeset_present:
    runs-on: ubuntu-22.04
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Extract branch name
        id: extract_branch
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      - name: Changeset file lookup  
        run: |
          pr_branch="${{steps.extract_branch.outputs.branch }}"
          files=$(gh pr diff $pr_branch --name-only)
          if [[ $files =~ \.changeset\/.*.md ]]; then
            echo "Changesets found!"
          else
            echo "There is no changeset file in your pull request."
            exit 1
          fi
