name: Changesets

on: [pull_request]
jobs:
  changeset_present:
    runs-on: ubuntu-22.04
    steps:
      - id: files
        name: Get changed files
        uses: jitterbit/get-changed-files@v1
        with:
          format: csv
      - name: Changeset file lookup  
        run: |
          if [[ "${{ steps.files.outputs.added_modified }}" =~ \.changeset\/.*.md ]]; then
            echo "Changesets found!"
          else
            echo "There is no changeset file in your pull request."
            exit 1
          fi

